import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/global/Footer";
import Header from "@/components/global/Header";
import "react-phone-input-2/lib/style.css";
import FormSecton from "@/components/global/FormSection";
import { getStrapiURL } from "@/lib/utils";
import { GlobalApi } from "@/types";
import { App } from "antd";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans", // expose as a CSS variable
});

export const metadata: Metadata = {
  title: "Xizec-The X factor in IT Consulting",
  description: "Generated by create next app",
};

async function loader() {
  const { fetchData } = await import("@/lib/api");

  const path = "/api/global";

  const baseUrl = getStrapiURL();

  const url = new URL(path, baseUrl);

  const data = await fetchData(url.href);

  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = (await loader()) as GlobalApi;
  if (!data) return null;

  const ContactData = data?.CommonData?.contacts;
  const FooterData = data?.Footer;
  const SocialLinks = data?.CommonData?.socialLinks;
  const FormSection = data?.FormSection;
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased scrollbar-hide`}>
        <App>
          <Header data={data} />
          {children}
          <FormSecton
            ContactData={ContactData}
            FormSection={FormSection}
            SocialLinks={SocialLinks}
          />
          <Footer
            ContactData={ContactData}
            FooterData={FooterData}
            SocialLinks={SocialLinks}
          />
        </App>
      </body>
    </html>
  );
}
